### PR TITLE
Add gem rails_admin

### PR DESCRIPTION
**Pull request by tatuan19**
## Related Tickets
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/41166)

## WHAT (optional)
- Thay admin page bằng giao diện admin của gem rails_admin

## HOW
- Add gem rails_admin
- Sử dụng theme rollincode cho rails_admin
- Xóa controllers, views cũ

## Evidence (Screenshot or Video)
image

### CODE REVIEW

**Comment by tatuan19** [comment]
ready

**Comment by quan191** [comment]
Ok

**Comment by datbk206** [comment]
ok

**Review by ghost — COMMENTED** [review]
merged

**Pull request merged**
